version: '3.8'

services:
  backend:
    build: .
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # ローカルのコード変更を即反映
      - ./models:/app/models
    env_file:
      - .env
    restart: unless-stopped
